### ISSUE TITLE
Correcting complex matrix length functions in lapack-wrapx in atlas-lapack module

### ISSUE THREAD

**Issue by ThatGeoGuy** [iraikov/chicken-lapack#3]
As mentioned at https://github.com/iraikov/chicken-lapack/issues/2#issuecomment-82746009, the `atlas-lapack` egg has a rather critical bug that should prevent any functions that operate over complex or double complex matrices from working. 

The basic issue is in the `lapack-wrapx` macro, which defines the length operation over complex / double complex vectors as `(lambda (v) (fx/ 2 (f32vector-length v)))`. In actuality, this makes no sense since we would be dividing the length of our vector `v` from the fixnum 2. Since this is fixnum division, this will almost always result in 2. The proposed fix is to change it such that: 

```
(lambda (v) (fx/ (f32vector-length v) 2))
```

However, I think the fix should also include a relevant test-case. I think in general the library is lacking test-cases, and could use some basic identities to prove that the functions are being called appropriately. They would also serve as examples for people who may wish to use the egg in the future. I'll be blunt, I could really use the examples myself, even though I consider myself fairly familiar with the library as it stands. 

I'm willing to make the fix and submit a pull request. Likewise, I will also try to construct some automated tests. Perhaps I should open a separate issue for adding tests?

**Comment by iraikov** [comment]
Agreed on the fix and the need for test cases. And yes a separated issue for adding tests would be good. Thanks for taking the lead on this.
