### ISSUE TITLE
Rename lapack-wrap and lapack-wrapx in atlas-lapack to atlas-wrap and atlas-wrapx 

### ISSUE THREAD

**Issue by ThatGeoGuy** [iraikov/chicken-lapack#4]
This is a minor grievance, but I think it would make things more consistent if the `lapack-wrap` and `lapack-wrapx` macros were renamed to `atlas-wrap` and `atlas-wrapx` respectively. 

I don't usually like submitting issues like this, but I think it would be valuable to distinguish between the macros that exist within `atlas-lapack.scm` and `lapack-extras.scm`, as the two macros are somewhat dissimilar at present (see https://github.com/ThatGeoGuy/chicken-lapack/tree/lapack-extras). Overall I think this will prevent anyone who might look at the code from confusing one as merely a copy of the other (though in many ways, they are very similar). 

Since the lapack-extras module is not yet merged into master, I think this can at present wait until that time, but I thought it valuable to bring up beforehand.

**Comment by iraikov** [comment]
This is fine with me, there is no reason to use the same names if the macros are actually different.
